### ISSUE TITLE
Console error message when opening modal windows

### ISSUE THREAD

**Issue by martindsouza** [OraOpenSource/apex-frontend-boost#88] opened 2016-05-12 17:43 UTC
![snip20160512_3](https://cloud.githubusercontent.com/assets/2925726/15224462/b1cd9730-1836-11e6-9bc8-0479e5fbaae6.png)

Not sure of impact on app yet but don't think it's good to have that error.

**Comment by vincentmorneau** [comment] 2016-06-13 03:16
@martindsouza I've been trying with browsersync 2.13.x and can't reproduce.

config.json:
```
"modal-demo": {
        "appURL": "https://apex.oracle.com/pls/apex/f?p=90880:1100",
        "srcFolder": "../afeb-demo/src",
        "distFolder": "../afeb-demo/dist"
    }
```

Config above is the UT showcase demo with modal screens. What was your config?

**Comment by vincentmorneau** [comment] 2016-08-02 14:16
The fix for https://github.com/OraOpenSource/apex-frontend-boost/issues/115 will help with modal handling. Closing this for now.

**Closed by vincentmorneau** 2016-08-02 14:16 UTC
Labels: bug
